create table t (id int primary key, name text);
create table t2 (j json);
create table t3 (j jsonb);
create table t4 (b bool);
create table t5 (t timestamptz);
create table t6 (f float);
create table t7 (i inet, c cidr);
create table t8 (i interval);
create table t9 (n numeric);
create table t10 (b bytea);
create table t11 (l line);
create table t12 (x xml);
