# Refer to https://github.com/marketplace/actions/rust-release-binary for more info
name: Docker Compose Actions Workflow
on:
  push:
    branches:
  # pull_request:
  # types: [opened, reopened]

jobs:
  unittest:
    name: unittest ${{ matrix.pgversion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pgversion: [12, 13, 14, 15, 16]
    env:
      PGVERSION: ${{ matrix.pgversion }}
    steps:
      - uses: actions/checkout@master
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: compose
        run: |
          docker-compose --version
          echo $PGVERSION
      - name: postgres
        run: docker-compose down --remove-orphans --rmi local || echo new or partial install
      - name: postgres
        run: docker-compose up -d postgres --no-deps
      - name: pgschema
        run: docker-compose up pgschema --no-deps --exit-code-from pgschema
      - name: pgtester
        run: docker-compose up pgtester --no-deps --exit-code-from pgtester
