name: Release workflow for tagged versions
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.2.19, v0.2.14a

env:
  GO_VERSION: 1.16

jobs:
  release-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./cmd/pgtester

      - name: Rename and compress
        run: |
          mv pgtester pgtester-amd64
          tar --owner=0 --group=0 -zcvf pgtester-amd64.tar.gz pgtester-amd64
          sha256sum pgtester-amd64 pgtester-amd64.tar.gz > SHA256SUM

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pgtester-amd64
            pgtester-amd64.tar.gz
            SHA256SUM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
